name: Daily Job Roundup

on:
  schedule:
    # 07:30 UTC every day == 13:00 IST every day
    - cron: '30 7 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libdrm2 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libxss1 libxtst6 libgbm1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run job fetcher & emailer
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          MAX_PER_BOARD: ${{ secrets.MAX_PER_BOARD }}
          MAX_TOTAL: ${{ secrets.MAX_TOTAL }}
        run: node fetch_and_email.js
