name: Daily Job Roundup

on:
  schedule:
    # 07:30 UTC = 13:00 IST every day
    - cron: '30 7 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install system deps for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \
            libatk1.0-0 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libxss1 \
            libxtst6 \
            fonts-liberation \
            libappindicator3-1 \
            xdg-utils

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Run job fetcher & emailer
        env:
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 465
          SMTP_SECURE: true
          SMTP_USER: ${{ secrets.SMTP_USER }}  # your Gmail address
          SMTP_PASS: ${{ secrets.SMTP_PASS }}  # Gmail App Password
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }} # same as Gmail usually
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          MAX_PER_BOARD: ${{ secrets.MAX_PER_BOARD }}
          MAX_TOTAL: ${{ secrets.MAX_TOTAL }}
        run: node fetch_and_email.js
